from sqlalchemy import Column, Integer, String, Boolean, DateTime, ForeignKey, Text, JSON
from sqlalchemy.orm import relationship
from datetime import datetime

from .database import Base

class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    name = Column(String(100), nullable=False)
    email = Column(String(100), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    college_org = Column(String(200), nullable=True) # From user signup requirements
    role = Column(String(20), default="user")
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    datasets = relationship("Dataset", back_populates="owner")
    reports = relationship("Report", back_populates="owner")

class Dataset(Base):
    __tablename__ = "datasets"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    filename = Column(String(255), nullable=False)
    file_path = Column(String(500), nullable=False)
    description = Column(Text, nullable=True)
    is_public = Column(Boolean, default=False)
    row_count = Column(Integer, default=0)
    col_count = Column(Integer, default=0)
    upload_date = Column(DateTime, default=datetime.utcnow)

    # Relationships
    owner = relationship("User", back_populates="datasets")
    analyses = relationship("AnalysisResult", back_populates="dataset")
    visualizations = relationship("Visualization", back_populates="dataset")
    reports = relationship("Report", back_populates="dataset")

class AnalysisResult(Base):
    __tablename__ = "analysis_results"

    id = Column(Integer, primary_key=True, index=True)
    dataset_id = Column(Integer, ForeignKey("datasets.id"))
    analysis_type = Column(String(50)) # e.g., 'eda', 'ml_classification', 'ml_regression', 'nlp_summary'
    result_json = Column(JSON, nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    dataset = relationship("Dataset", back_populates="analyses")

class Visualization(Base):
    __tablename__ = "visualizations"

    id = Column(Integer, primary_key=True, index=True)
    dataset_id = Column(Integer, ForeignKey("datasets.id"))
    chart_type = Column(String(100)) # e.g., 'histogram', 'scatter', 'heatmap'
    chart_config_json = Column(JSON, nullable=False) # Plotly JSON schema
    explanation = Column(Text, nullable=True) # 10-line explanations generated by NLP/logic
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    dataset = relationship("Dataset", back_populates="visualizations")

class Report(Base):
    __tablename__ = "reports"

    id = Column(Integer, primary_key=True, index=True)
    dataset_id = Column(Integer, ForeignKey("datasets.id"))
    user_id = Column(Integer, ForeignKey("users.id"))
    report_path = Column(String(500), nullable=False) # Extracted PDF URL/Cloudinary
    generated_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    dataset = relationship("Dataset", back_populates="reports")
    owner = relationship("User", back_populates="reports")
