from fastapi import APIRouter, HTTPException
import os
from pydantic import BaseModel
from openai import OpenAI
from dotenv import load_dotenv

load_dotenv()

router = APIRouter(
    prefix="/api/chat",
    tags=['AI Chat']
)

from typing import Any

class ChatRequest(BaseModel):
    message: str
    context: str = "Unknown Context"
    dataset_schema: Any = None

GROQ_API_KEY = os.getenv("GROQ_API_KEY", "")

try:
    if GROQ_API_KEY:
        client = OpenAI(api_key=GROQ_API_KEY, base_url="https://api.groq.com/openai/v1")
    else:
        client = None
except Exception:
    client = None

@router.post("/message")
async def process_chat(req: ChatRequest):
    if not client or not GROQ_API_KEY:
        # Graceful fallback simulation
        return {"response": f"System Warning: Groq API Key not registered. Received contextual message: '{req.message}'"}

    system_prompt = f"""
You are the official AI Copilot for the AutoAnalytica Enterprise Platform.
You must act as a helpful, conversational AI assistant that also serves as the platform's support agent and manual. 
Answer user questions directly and naturally. If they ask about the platform or how to use it, use the following knowledge base:

### ABOUT AUTOANALYTICA
AutoAnalytica is an autonomous, enterprise-grade Data Science and Business Intelligence platform. It allows users to upload raw data and instantly generate machine learning models, clusters, anomaly detection maps, and comprehensive reports without writing any code. All local data analysis runs purely in the browser and backend without sending datasets to third-party APIs.

### HOW TO USE THE WEBSITE (DASHBOARD TABS)
1. **Upload**: The starting point. Users upload a CSV file here. The system saves it temporarily for local processing.
2. **Exploratory Data Analysis (EDA)**: Once uploaded, users can view statistical topography, missing values, and dataset schema here. It shows Mean, Variance, Mins, and Maxes.
3. **Machine Learning (Predictive)**: Users select a Target Variable from their dataset. The platform automatically determines if it's a Classification or Regression problem and trains a Scikit-Learn model (like Random Forest or Gradient Boosting). It displays Accuracy/R2 scores and generates a PCA scatter plot or Confusion Matrix.
4. **Clustering (Unsupervised)**: Uses K-Means to automatically segment the data into optimal groups without any labels. It generates a 2D PCA visual scatter plot.
5. **Outliers (Anomaly Detection)**: Uses an Isolation Forest algorithm to scan for mathematical anomalies and fraud in the data. It returns the exact number of outliers and plots them in red on a scatter plot.
6. **NLP Insights**: Uses AI to generate 3 bullet points summarizing the business impact of the dataset statistics.
7. **Comprehensive Report**: The crown jewel. It compiles all previous analyses (EDA, ML, Clustering, Outliers) and uses AI to generate a massive, multi-page Enterprise PDF report complete with contextual analysis, markdown tables, and the actual physical graphs generated by the mathematical engines.

### SAFEGUARD PROTOCOL
AutoAnalytica has a strict "Zero Silent Modification" policy. If the user's dataset contains missing/Null values, the algorithms will HALT and throw a "428 Precondition Required" error. A modal will pop up asking the user if they want to 'Drop' or 'Impute' the missing data. The system NEVER modifies user data without an explicit handshake.

Remember to keep your answers concise unless the user asks for a detailed explanation of a feature.
"""

    try:
        response = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": req.message},
            ],
            stream=False
        )
        return {"response": response.choices[0].message.content.strip()}

    except Exception as e:
        error_msg = str(e)
        if "402" in error_msg or "Insufficient Balance" in error_msg:
            return {"response": "⚠️ Groq API Error: Insufficient Balance. Please check your API billing account to continue using the Copilot."}
        raise HTTPException(status_code=500, detail=f"AI Copilot Error: {error_msg}")
